language: cpp

script:
- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Coverage -DCPACK_GENERATOR="TGZ"
- cmake --build _build
- cmake --build _build --target install
- cmake --build _build --target unit_tests_coverage 
- cmake --build _build --target package

# Генерация документации
after_success:
  - git clone -b develop https://github.com/mikaelkg/BSTTree
  - cd BSTTree
  - git config --global push.default simple
  - git config user.name "Travis CI"
  - git config user.email "travis@travis-ci.org"
  - doxygen docs/doxygen.conf
  - ls | grep "[^docs]" | xargs rm -rf
  - mv docs/html/* . && rm -rf docs
  - git add .
  - git commit -m "documentation"
  - git push --force "https://${GH_REPO_TOKEN}@github.com/mikaelkg/BSTTree.git" > /dev/null 2>&1

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - lcov
      - graphviz
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
